# Generated by Django 5.0.3 on 2024-03-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clutch',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='clutch',
            old_name='Item_Service_No',
            new_name='item_service_no',
        ),
        migrations.RenameField(
            model_name='clutch',
            old_name='Part_No',
            new_name='part_no',
        ),
    ]
