# Generated by Django 5.0.3 on 2024-03-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_description_clutch_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clutch',
            table='clutch',
        ),
    ]
