# Generated by Django 5.0.3 on 2024-03-16 15:58

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Clutch = apps.get_model('myapp', 'Clutch')
    Clutch.objects.bulk_create([
        Clutch(item_service_no=1, part_no='513900', description='Case'),
        Clutch(item_service_no=2, part_no='513739', description='17/16\" Fan Clutch Wrench'),
        Clutch(item_service_no=3, part_no='413742', description='17/16\" Fan Clutch Wrench'),
        # Add more objects as needed
    ])

class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0003_alter_clutch_table'),  # Replace with the previous migration
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]